Updating the gradlew reference
inductiveautomation/ignition-sdk-examples pull request #83
Opened 2021-10-28 23:36 UTC by keith-gamble

In the getting started it calls the `gradlew` file as having the `.sh` file extension, but it doesn't! So it should be executed with`sh`

This is in reference to issue #82

2021-11-12 00:44 UTC, PerryAJ commented
Thanks Keith, but I think the leading `sh` is also unnecessary.  I believe the gradle wrapper script used to have the .sh extension, but `./gradlew <task>` has been what I use.

2021-11-12 00:45 UTC, PerryAJ requested changes

2021-11-12 00:45 UTC, PerryAJ commented on perspective-component/README.md
> +sh ./gradlew buildModule
think we can omit the leading `sh` here

2022-02-16 16:24 UTC, keith-gamble commented
Closing, since it is resolved in #85

2022-02-16 16:24 UTC, closed without merging